import type { MemoryOSSettingsIds } from "./settingsCardTemplateTypes";

/**
 * 功能：构建 MemoryOS 设置面板 tooltip 目录。
 * 参数：
 *   ids：设置面板 DOM ID 集合。
 * 返回：
 *   Record<string, string>：键为控件 ID，值为提示文本。
 */
export function buildSettingsTooltipCatalog(ids: MemoryOSSettingsIds): Record<string, string> {
  return {
    [ids.drawerToggleId]: "展开或收起 MemoryOS 设置面板。",
    [ids.drawerContentId]: "MemoryOS 设置内容区域。",
    [ids.drawerIconId]: "展开或收起设置面板。",
    [ids.badgeId]: "显示当前插件版本号。",
    [ids.searchId]: "按关键词筛选设置项。",
    [ids.tabMainId]: "切换到主设置面板。",
    [ids.tabAiId]: "切换到 AI 规则面板。",
    [ids.tabDbId]: "切换到数据管理面板。",
    [ids.tabTemplateId]: "切换到世界模板面板。",
    [ids.tabAuditId]: "切换到审计回滚面板。",
    [ids.tabAboutId]: "切换到关于面板。",
    [ids.panelMainId]: "主设置面板。",
    [ids.panelAiId]: "AI 规则面板。",
    [ids.panelDbId]: "数据管理面板。",
    [ids.panelTemplateId]: "世界模板面板。",
    [ids.panelAuditId]: "审计回滚面板。",
    [ids.panelAboutId]: "关于面板。",
    [ids.enabledId]: "MemoryOS 总开关。",
    [ids.aiModeEnabledId]: "启用 AI 抽取。",
    [ids.aiModeStatusLightId]: "显示 LLMHub 连接状态。",
    [ids.contextMaxTokensId]: "限制注入上下文长度。",

    [ids.recordFilterEnabledId]: "控制是否开启记录过滤。",
    [ids.recordFilterLevelId]: "选择过滤强度。",
    [ids.recordFilterTypeHtmlId]: "是否过滤 HTML 标签。",
    [ids.recordFilterTypeXmlId]: "是否过滤 XML 标签。",
    [ids.recordFilterTypeJsonId]: "是否过滤 JSON 结构。",
    [ids.recordFilterTypeCodeblockId]: "是否过滤代码块。",
    [ids.recordFilterTypeMarkdownId]: "是否过滤 Markdown 噪声。",
    [ids.recordFilterCustomCodeblockEnabledId]: "开启后不再清理全部代码块，只清理你指定标签的代码块。",
    [ids.recordFilterCustomCodeblockTagsId]: "填写要清理的代码块标签，支持逗号或换行分隔，默认建议保留 rolljson。",
    [ids.recordFilterJsonModeId]: "设置 JSON 文本提取模式。",
    [ids.recordFilterJsonKeysId]: "设置 smart 模式提取键。",
    [ids.recordFilterPureCodePolicyId]: "设置纯代码消息处理方式。",
    [ids.recordFilterPlaceholderId]: "设置占位策略写入文本。",
    [ids.recordFilterCustomRegexEnabledId]: "控制是否启用自定义正则。",
    [ids.recordFilterCustomRegexRulesId]: "每行一条清理规则。",
    [ids.recordFilterMaxTextLengthId]: "限制单条保存最大字符。",
    [ids.recordFilterMinEffectiveCharsId]: "限制最小有效字符数。",
    [ids.recordFilterPreviewInputId]: "输入测试文本。",
    [ids.recordFilterPreviewBtnId]: "点击预览过滤结果。",
    [ids.recordFilterPreviewOutputId]: "显示预览结果，不写数据库。",
    [ids.recordFilterSectionId]: "记录过滤设置分组。",
    [ids.recordFilterDetailWrapId]: "记录过滤详细配置区域。",

    [ids.autoCompactionId]: "自动压缩历史事件。",
    [ids.compactionThresholdId]: "达到这个数量后开始压缩。",
    [ids.dbCompactionDividerId]: "数据压缩与清理分组标题。",
    [ids.dbCompactBtnId]: "立即执行一次压缩。",
    [ids.recordEditorBtnId]: "打开记录编辑器。",
    [ids.dbExportBtnId]: "导出当前聊天记忆。",
    [ids.dbImportBtnId]: "导入记忆到当前聊天。",
    [ids.dbClearBtnId]: "清空当前聊天记忆。",
    [ids.testPingBtnId]: "测试通信是否正常。",
    [ids.testHelloBtnId]: "测试与 LLMHub 握手。",

    [ids.templateRefreshBtnId]: "刷新模板列表。",
    [ids.templateForceRebuildBtnId]: "从世界书重建模板。",
    [ids.templateActiveSelectId]: "选择要启用的模板。",
    [ids.templateLockId]: "锁定当前模板。",
    [ids.templateSetActiveBtnId]: "应用当前模板。",
    [ids.templateListId]: "展示当前聊天绑定的世界模板结构。",
    [ids.wiPreviewBtnId]: "预览写回内容。",
    [ids.wiWritebackBtnId]: "写回事实和摘要。",
    [ids.wiWriteSummaryBtnId]: "只写回摘要。",
    [ids.wiPreviewId]: "显示世界书写回预览内容。",
    [ids.logicTableEntitySelectId]: "选择实体类型。",
    [ids.logicTableRefreshBtnId]: "刷新逻辑表。",
    [ids.logicTableContainerId]: "显示并编辑逻辑表内容。",
    [ids.auditCreateSnapshotBtnId]: "创建回滚快照。",
    [ids.auditRefreshBtnId]: "刷新审计记录。",
    [ids.auditListId]: "显示审计历史和快照列表。",
  };
}
