import { describe, expect, it } from 'vitest';
import { deriveVectorMemoryViewerItems } from '../src/ui/vectorMemoryViewer';
import type { VectorMemoryViewerSnapshot } from '../../SDK/stx';

function buildSnapshot(): VectorMemoryViewerSnapshot {
    return {
        chatKey: 'chat:test',
        generatedAt: 1000,
        totalCount: 3,
        archivedCount: 1,
        sourceMissingCount: 1,
        needsRebuildCount: 1,
        recentHitCount: 1,
        longUnusedCount: 1,
        items: [
            {
                chunkId: 'chunk-a',
                chatKey: 'chat:test',
                content: '阿尔法记忆内容较完整',
                preview: '阿尔法记忆内容较完整',
                contentHash: 'ha',
                contentLength: 10,
                createdAt: 100,
                sourceRecordKey: 'fact:a',
                sourceRecordKind: 'fact',
                sourceLabel: '事实 A',
                sourceDetail: '来源 A',
                ownerActorKey: 'actor:a',
                ownerActorLabel: '角色 A',
                sourceScope: 'self',
                memoryType: 'identity',
                memorySubtype: 'trait',
                participantActorKeys: [],
                participantActorLabels: [],
                anchorMessageId: 'msg-a',
                sourceMessageIds: ['msg-a'],
                sourceTraceKind: 'extract',
                sourceReason: 'manual',
                sourceViewHash: 'view-a',
                sourceSnapshotHash: 'snap-a',
                sourceRepairGeneration: 0,
                embeddingModel: 'model-a',
                embeddingDimensions: 1024,
                statusKind: 'recent_hit',
                statusLabel: '最近命中',
                statusTone: 'success',
                statusReasons: [],
                isArchived: false,
                sourceMissing: false,
                needsRebuild: false,
                duplicateCount: 1,
                usage: {
                    totalHits: 5,
                    selectedHits: 2,
                    hitsIn7d: 3,
                    hitsIn30d: 5,
                    lastHitAt: Date.now(),
                    lastSelectedAt: Date.now(),
                    lastQuery: '谁最重要',
                    lastScore: 0.91,
                },
            },
            {
                chunkId: 'chunk-b',
                chatKey: 'chat:test',
                content: '贝塔记忆',
                preview: '贝塔记忆',
                contentHash: 'hb',
                contentLength: 4,
                createdAt: 200,
                sourceRecordKey: 'summary:b',
                sourceRecordKind: 'summary',
                sourceLabel: '摘要 B',
                sourceDetail: '来源 B',
                ownerActorKey: 'actor:b',
                ownerActorLabel: '角色 B',
                sourceScope: 'group',
                memoryType: 'event',
                memorySubtype: 'major_plot_event',
                participantActorKeys: ['actor:a'],
                participantActorLabels: ['角色 A'],
                anchorMessageId: null,
                sourceMessageIds: [],
                sourceTraceKind: 'extract',
                sourceReason: 'repair',
                sourceViewHash: 'view-b',
                sourceSnapshotHash: 'snap-b',
                sourceRepairGeneration: 2,
                embeddingModel: 'model-b',
                embeddingDimensions: 1024,
                statusKind: 'needs_rebuild',
                statusLabel: '建议重建',
                statusTone: 'warning',
                statusReasons: ['来源记录已更新'],
                isArchived: false,
                sourceMissing: false,
                needsRebuild: true,
                duplicateCount: 1,
                usage: {
                    totalHits: 0,
                    selectedHits: 0,
                    hitsIn7d: 0,
                    hitsIn30d: 0,
                    lastHitAt: null,
                    lastSelectedAt: null,
                    lastQuery: null,
                    lastScore: null,
                },
            },
            {
                chunkId: 'chunk-c',
                chatKey: 'chat:test',
                content: '伽马记忆',
                preview: '伽马记忆',
                contentHash: 'hc',
                contentLength: 4,
                createdAt: 300,
                sourceRecordKey: null,
                sourceRecordKind: 'unknown',
                sourceLabel: '未知来源',
                sourceDetail: '来源缺失',
                ownerActorKey: null,
                ownerActorLabel: null,
                sourceScope: null,
                memoryType: null,
                memorySubtype: null,
                participantActorKeys: [],
                participantActorLabels: [],
                anchorMessageId: null,
                sourceMessageIds: [],
                sourceTraceKind: null,
                sourceReason: null,
                sourceViewHash: null,
                sourceSnapshotHash: null,
                sourceRepairGeneration: null,
                embeddingModel: 'model-c',
                embeddingDimensions: 1024,
                statusKind: 'source_missing',
                statusLabel: '来源丢失',
                statusTone: 'danger',
                statusReasons: ['缺少来源'],
                isArchived: true,
                sourceMissing: true,
                needsRebuild: false,
                duplicateCount: 2,
                usage: {
                    totalHits: 1,
                    selectedHits: 0,
                    hitsIn7d: 0,
                    hitsIn30d: 1,
                    lastHitAt: Date.now() - 40 * 24 * 60 * 60 * 1000,
                    lastSelectedAt: null,
                    lastQuery: '旧问题',
                    lastScore: 0.1,
                },
            },
        ],
    };
}

describe('vectorMemoryViewer', () => {
    it('按异常快捷筛选与当前角色筛选返回正确结果', () => {
        const snapshot = buildSnapshot();
        const items = deriveVectorMemoryViewerItems(snapshot, {
            keyword: '',
            sourceKind: 'all',
            statusKind: 'all',
            actorKey: '__all__',
            sortMode: 'recent_hit',
            timeFilter: '__all__',
            quickRecentHit: false,
            quickLongUnused: false,
            quickAbnormal: true,
            quickCurrentActor: true,
            activeActorKey: 'actor:a',
            testResult: null,
        });
        expect(items.map((item) => item.item.chunkId)).toEqual(['chunk-b']);
    });

    it('在测试结果模式下按命中顺序返回并保留测试信息', () => {
        const snapshot = buildSnapshot();
        const items = deriveVectorMemoryViewerItems(snapshot, {
            keyword: '',
            sourceKind: 'all',
            statusKind: 'all',
            actorKey: '__all__',
            sortMode: 'recent_hit',
            timeFilter: '__all__',
            quickRecentHit: false,
            quickLongUnused: false,
            quickAbnormal: false,
            quickCurrentActor: false,
            activeActorKey: null,
            testResult: {
                query: '测试',
                testedAt: Date.now(),
                rerankApplied: true,
                hitCount: 2,
                selectedCount: 1,
                hits: [
                    {
                        chunkId: 'chunk-b',
                        sourceRecordKey: 'summary:b',
                        sourceRecordKind: 'summary',
                        sourceLabel: '摘要 B',
                        preview: '贝塔记忆',
                        vectorScore: 0.8,
                        initialRank: 2,
                        rerankedRank: 1,
                        finalRank: 1,
                        matchedInRecall: true,
                        enteredContext: true,
                        reasonCodes: ['vector'],
                    },
                    {
                        chunkId: 'chunk-a',
                        sourceRecordKey: 'fact:a',
                        sourceRecordKind: 'fact',
                        sourceLabel: '事实 A',
                        preview: '阿尔法记忆',
                        vectorScore: 0.7,
                        initialRank: 1,
                        rerankedRank: 2,
                        finalRank: null,
                        matchedInRecall: true,
                        enteredContext: false,
                        reasonCodes: ['vector'],
                    },
                ],
            },
        });
        expect(items.map((item) => item.item.chunkId)).toEqual(['chunk-b', 'chunk-a']);
        expect(items[0]?.testHit?.finalRank).toBe(1);
        expect(items[1]?.testHit?.rerankedRank).toBe(2);
    });
});
